config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'

  resources :bookings, only: :show

  namespace :user do
    resources :bookings, only:[ :index ]
  end

  namespace :chef do
    resources :bookings, only:[ :index ]
  end

  resources :menus, only: [:new, :create, :edit, :update, :destroy]

  resources :menus, only: [:index, :show] do
    resources :bookings, only: [ :new, :create ]
  end

  resources :users, only: [:index, :show]


  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  validates :location, presence: true
  validates :datetime, presence: true
  validates :guests, presence: true, numericality: true
  validate :booking_date_cannot_be_in_the_past
  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def booking_date_cannot_be_in_the_past
    if datetime < Date.today
      errors.add(:datetime, "Cannot be in the past")
    end
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates_associated :bookings
  validates :name, :price, :preparation_time, :min_guests, :max_guests, :category, presence: true
  validates :category, inclusion: { in:
    %w(Italian Chinese Japanese Belgian French Indian Lebanese Persian Italian Etiopian Vietnameese English Spanish Carribean Greek)}
  has_attachments :photos, maximum: 4
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true, uniqueness: true
  has_many :bookings
  has_many :menus
  has_attachment :photo

  #  These validations are not needed as we do not want to require them on sign up
  # validates :first_name, :last_name, presence: true
  # validates :description, presence: true, length: { in: 0..150 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :postal_address, :photo, :description])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]

  def new
    @booking = Booking.new
    @booking.menu = Menu.find(params[:menu_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.menu = Menu.find(params[:menu_id])
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end



  def show
    @hash = Gmaps4rails.build_markers(@booking) do |booking, marker|
      marker.lat booking.latitude
      marker.lng booking.longitude
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:location, :datetime, :guests, :rating)
  end
end

app/controllers/chef/bookings_controller.rb
class Chef::BookingsController < ApplicationController

# this is controller to view bookings as a chef - aka the 'orders' you have from people who have booked you.

  before_action :set_user, only: [:show]
  def index
    @bookings = Booking.where(chef: current_user)
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  def index
    @menus = Menu.all
    @selected_category = params[:category]
    @selected_guests = params[:guests]
    if @selected_guests.empty?
      @selected_menus = @menus.select { |menu| menu.category.downcase == @selected_category.downcase }
    else
      @selected_menus = @menus.select { |menu| menu.category.downcase == @selected_category.downcase && menu.min_guests < @selected_guests.to_i && @selected_guests.to_i < menu.max_guests }
    end
  end

  def show
    @chef = @menu.user
    session[:menu_id] = @menu.id
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.user = current_user
    if @menu.save
      redirect_to menu_path(@menu)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @menu.update(menu_params)
    redirect_to menu_path(@menu)
  end

  def destroy
    @menu.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:user_id, :name, :price, :preparation_time, :min_guests, :max_guests, :starter, :main, :dessert, :category, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: :home


  def home
    @categories = %w(Italian Chinese Japanese Belgian French Indian Lebanese Persian Etiopian Vietnameese English Spanish Carribean Greek)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    if session[:menu_id] && (menu = Menu.where(id: session[:menu_id]).first)
      "/menus/#{menu.id}"
    end
  end
end

app/controllers/user/bookings_controller.rb
class User::BookingsController < ApplicationController

  # this is controller to interact with bookings as a user(customer) - aka the 'orders' you have placed to book a chef.
  def index
    @bookings_as_user = Booking.where(user: current_user)
    @bookings_as_chef = Booking.where(menu: current_user.menus)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show]

  def index
    @users = User.all
  end
  def show
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :postal_address, :description, :admin, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
<% if @booking.menu.photos? %>
        <% image = cl_image_path @booking.menu.photos[0].path %>
<% else %>
        <% image = 'http://unsplash.it/1000/800' %>
<% end %>

<div class="banner"  id="booking-form-banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image %>);">
  <div class="banner-content">
    <div class="form-wrapper" id="wrapper-booking-form">
      <div class = "container">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-center">
            <div class="form" id="booking-form">
                <h2> Make a Booking </h2>
              <%= simple_form_for [@booking.menu, @booking] do |f| %>
                <%= f.input :location %>
                <%= f.input :datetime, label: 'Date and Time' %>
                <%= f.input :guests, label: 'Headcount', collection:(@booking.menu.min_guests..@booking.menu.max_guests).to_a %>
                <%= f.submit "Make a booking", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
 </div>
</div>

app/views/bookings/show.html.erb
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV["GOOGLE_API_BROWSER_KEY"]}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag "application" %>

  <% if @booking.menu.photos? %>
        <% image = cl_image_path @booking.menu.photos[0].path %>
  <% else %>
        <% image = "https://unsplash.it/1000/800" %>
  <% end %>
  <div class="banner" id="half-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image %>);"">

    <div class="banner-content">
      <h1><%= @booking.menu.name %></h1>
    </div>
  </div>

  <div class="wrapper-user">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <div class="user-card">
            <div class="user-card-title text-center">
              <h2> Your Chef </h2>
            </div>
              <div class="chef-card-photo text-center">
                <% if @booking.menu.user.photo? %>
                  <%= cl_image_tag @booking.menu.user.photo.path, width: 200, height: 200, crop: :fill, class: "img-circle" %>
                <% else %>
                  <%= image_tag "logo.png", class: "img-circle avatar-menu text-center" %>
                <% end %>
              </div>
            <div class="user-card-details text-center">
              <ul class="text-center">
                <li> <%= @booking.menu.user.first_name %><%= @booking.menu.user.last_name %></li>
                <li> <%= @booking.menu.user.description %></li>
              </ul>
            </div>
              <%= link_to "Chef's profile", new_menu_booking_path(@booking.menu), {class: "btn btn-primary user-card-btn"} %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6">
          <div class="user-card">
            <div class="user-card-title text-center">
              <h2> Review your menu </h2>
            </div>
            <div class="user-card-details">
              <ul class="text-center">
                <li><i class="fa fa-calendar" aria-hidden="true"> </i> <%= @booking.datetime.strftime("%A %d %B %H:%M") %></li>
                <li><i class="fa fa-map-marker" aria-hidden="true"> </i> <%= @booking.location %></li>
                <li> <i class="fa fa-money" aria-hidden="true"></i> £<%= @booking.menu.price %> p/p </li>
                <li> <i class="fa fa-cutlery" aria-hidden="true"></i> <%= @booking.menu.category %></li>
                <li> <i class="fa fa-users" aria-hidden="true"></i> <%= @booking.guests %></li>
                <li> <h3>Starter</h3><p> <%= @booking.menu.starter %></p></li>
                <li> <h3>Main Course</h3><p> <%= @booking.menu.main %></p></li>
                <li> <h3>Dessert</h3><p> <%= @booking.menu.dessert %></p></li>
                <li> <%= link_to "See all my bookings", user_bookings_path, class: "btn btn-danger" %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>




<%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV["GOOGLE_API_BROWSER_KEY"]}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
  <%= javascript_include_tag "application" %>

 <div class="wrapper-user">
  <div class="container">
  <div id="map" style="width: 100%; height: 600px;"></div>
  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
      $(document).on('ready', function() {
        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
            handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
            handler.getMap().setZoom(14);
          }
        });
      });
    <% end %>
  <% end %>
    <%= yield(:after_js) %>
  </body>
  </div>
</div>

app/views/chef/bookings/index.html.erb
<h1 class="text-center"> Bookings </h1>

<div class="container">
  <div class="row">
    <% @bookings.each do |booking| %>

       <p> <%= booking.menu_id %> </p>
       <p> <%= booking.location %> </p>
       <p> <%= booking.time %> </p>
       <p> <%= booking.guests %> </p>
     <%= link_to "See Details", user_booking_path, {class: "btn-btn-danger btn-lg"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Chef at home</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/menus/_card.html.erb
<% if menu.photos? %>
        <% image = cl_image_path menu.photos[0].path %>
<% else %>
        <% image = 'http://placehold.it/350x150' %>
<% end %>

<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image %>)"">

  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2> <%= menu.name %> </h2>
    <p> <%= menu.category %> </p>
  </div>
  <% if menu.user.photo? %>
    <%= cl_image_tag menu.user.photo.path, crop: :thumb, gravity: :face, class: "card-user avatar" %>
  <% else %>
    <%= image_tag "logo.png", class: "card-user avatar" %>
  <% end %>
  <%= link_to "", menu_path(menu.id), class: "card-link" %>
</div>

app/views/menus/_form.html.erb
 <%= simple_form_for @menu do |f| %>
  <%= f.input :name, placeholder: "What is the name?" %>
  <%= f.input :price, placeholder: "How much per person?" %>
  <%= f.input :preparation_time, placeholder: "How long will it take to cook?" %>
  <%= f.input :min_guests, collection: (1..100) %>
  <%= f.input :max_guests, collection: (1..250) %>
  <%= f.input :starter, placeholder: "Enter a brief description of the starter" %>
  <%= f.input :main, placeholder: "Enter a brief description of the main" %>
  <%= f.input :dessert, placeholder: "Enter a brief description of the dessert" %>
  <%= f.input :category, collection: ["Italian", "Chinese", "Japanese", "Belgian", "French", "Indian", "Lebanese", "Persian", "Etiopian", "Vietnameese", "English", "Spanish", "Carribean", "Greek"] %>
  <%= f.input :photos, as: :attachinary, hint: "Upload photos of your menu. Max 4 photos" %>

  <%= f.button :submit, { class: "btn btn-danger wide-btn"} %>
<% end %>

app/views/menus/show.html.erb
<% if @menu.photos? %>
  <% image = cl_image_path @menu.photos[0].path, gravity: :center, crop: :lfill %>
<% else %>
  <% image = 'http://placehold.it/350x150' %>
<% end %>

<div class="banner" id="half-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image %>)"">


  <div class="banner-content text-center">
    <h1><%= @menu.name %></h1>
  </div>
</div>

<div class="wrapper-user">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="user-card">
          <div class="user-card-title text-center">
            <h2> Your Chef </h2>
          </div>
          <div class="chef-card-photo text-center">
            <% if @menu.user.photo? %>
              <%= cl_image_tag @menu.user.photo.path, width: 200, height: 200, crop: :fill, class: "img-circle" %>
            <% else %>
              <%= image_tag "logo.png", class: "img-circle avatar-menu text-center" %>
            <% end %>
          </div>
          <div class="user-card-details text-center">
            <ul class="text-center">
              <li> <%= @chef.first_name %> <%= @chef.last_name %></li>
              <li> <%= @chef.description %></li>
            </ul>
          </div>
          <% if user_signed_in? %>
            <%= link_to "Chef's profile", new_menu_booking_path(@menu), {class: "btn btn-primary user-card-btn"} %>
          <% else %>
            <%= link_to "Chef's profile", new_user_registration_path, {class: "btn btn-primary user-card-btn"} %>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="user-card">
          <div class="user-card-title text-center">
            <h2> Review your menu </h2>
          </div>
          <div class="user-card-details">
            <ul class="text-center">
              <li> <i class="fa fa-money" aria-hidden="true"></i> £<%= @menu.price %> p/p </li>
              <li> <i class="fa fa-cutlery" aria-hidden="true"></i> <%= @menu.category %></li>
              <li> <i class="fa fa-users" aria-hidden="true"></i> from <%= @menu.min_guests %> to <%= @menu.max_guests %> </li>
              <li> <h3>Starter</h3><p> <%= @menu.starter %></p></li>
              <li> <h3>Main Course</h3><p> <%= @menu.main %></p></li>
              <li> <h3>Dessert</h3><p> <%= @menu.dessert %></p></li>
            </ul>
          </div>
            <% if user_signed_in? %>
            <%= link_to "Book this menu now", new_menu_booking_path(@menu), {class: "btn btn-danger user-card-btn"} %>
            <% else %>
            <%= link_to "Book this menu now", new_user_registration_path, {class: "btn btn-danger user-card-btn"} %>
            <% end %>
        </div>
      </div>
    </div>
  </div>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner " role="listbox">
    <div class="item carousel-height active">
      <% image = cl_image_path @menu.photos[0].path, width: 500, height: 400, gravity: :center, crop: :lfill %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item carousel-height">
      <% image = cl_image_path @menu.photos[1].path, width: 500, height: 400, gravity: :center, crop: :lfill %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item carousel-height">
      <% image = cl_image_path @menu.photos[2].path, width: 500, height: 400, gravity: :center, crop: :lfill %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <video autoplay loop poster="polina.jpg" id="bgvid">
    <source src="https://s3.amazonaws.com/distill-videos/videos/processed/7/cookies.mp4.mp4" type="video/mp4">
<!--     <source src="https://a0.muscache.com/airbnb/static/Croatia-P1-0.webm" type="video/webm"> -->
  </video>
  <div class="banner-content text-center">
    <div class="container">
      <div class="row">

        <div class="col-xs-12">
          <div class="banner-text">
            <h1 class="text-jumbo">A personal chef at home?</h1>
            <h4>Choose a Menu, Choose a Chef, live the ultimate experience </h4>
            <span class="element"></span>
          </div>
        </div>



        <div class="col-xs-12">
          <div class="banner-form text-center">
             <%= form_tag(menus_path, :method => "get", id: "search-form", class: "navbar form-inline") do %>
                <%= select_tag :category, options_for_select(@categories), :prompt => "What type of Menu?", :class => "form-control" %>
                <%= select_tag :guests, options_for_select((1..10)), :prompt => "Number of guest", :class => "form-control"  %>
                <%= submit_tag "Research", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag 'logo.png' %>
    </a>

    <h2>Chef@home</h2>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% categories = %w(Italian Chinese Japanese Belgian French Indian Lebanese Persian Etiopian Vietnameese English Spanish Carribean Greek)
 %>

    <%= form_tag(menus_path, :method => "get", id: "nav-search-form", class: "navbar-wagon-search") do %>
      <%= select_tag :category, options_for_select(categories), :prompt => "What type of Menu?", :class => "form-control navbar-wagon-search-input", :id => "search-category" %>
      <%= select_tag :guests, options_for_select((1..10)), :prompt => "Number of guest", :class => "form-control navbar-wagon-search-input", :id => "search-num-guests"  %>
      <%= submit_tag "Research", class: "btn btn-primary" %>
    <% end %>

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Team</a>

    <!-- Profile picture and dropdown -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo? %>
            <%= cl_image_tag current_user.photo.path, crop: :fill, class: "avatar dropdown-toggle", id:"navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "logo.png", class: "avatar dropdown-toggle", id:"navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><a href="#">Dashboard</a></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
      <%= link_to "Add new meal", new_menu_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, { class: "navbar-wagon-item navbar-wagon-link"} %>
      <%= link_to "Log in", new_user_session_path, { class: "navbar-wagon-item navbar-wagon-button btn"} %>
    <% end %>

    <!-- Button (call-to-action) -->
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper-user">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <div class="user-card text-center">
          <h1>My Profile</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="user-card">
          <div class="user-card-info">
            <div class="user-card-photo">
            <!-- This image_tag needs to be altered when attachinary is implemented -->
              <% if @user.photo? %>
                <%= cl_image_tag @user.photo.path, width: 240, height: 240, crop: :fill, class: "img-circle" %>
              <% else %>
                <%= image_tag "logo.png", class: "avatar-xl" %>
              <% end %>
            </div>
            <div class="user-card-details">
              <h2>Account details </h2>

              <p><strong>Name:</strong> <%= "#{@user.first_name} #{@user.last_name}" %></p>
              <p><strong>Email:</strong> <%= @user.email %></p>
              <p><strong>Address:</strong> <%= @user.postal_address %></p>

              <%= link_to "Edit", edit_user_registration_path, { class: "btn btn-danger user-card-btn" } %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="user-card">
          <div class="user-card-title text-center">
            <h2>My menus</h2>
          </div>
          <div class="user-card-details">
            <% if @user.menus.count == 0 %>
              <div class="user-card-empty-list text-center">
                <p>You don't have any menus yet!</p>
              </div>
            <% else %>
              <% @user.menus.each do |menu| %>
                <div class="user-card-list">

                    <% if menu.photos? %>
                      <%= cl_image_tag menu.photos[0].path, crop: :fill, class: "avatar" %>
                    <% else %>
                      <%= image_tag "logo.png", class: "avatar" %>
                    <% end %>


                  <%= link_to menu.name, menu_path(menu), { class: "user-card-list-name"} %>
                  <!-- The link below needs to be linked to the menu#edit path - not yet created -->
                  <%= link_to "Edit", edit_menu_path(menu), { class: "btn btn-danger list-edit-btn" } %>
                  <%= link_to "Delete", menu_path(menu), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger list-delete-btn" %>
                </div>
              <% end %>
            <% end %>
          </div>
          <!-- This link needs to be linked to the menu#new path - not yet created -->
          <%= link_to "Add new menu", new_menu_path, { class: "btn btn-danger user-card-btn" } %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="user-card">
          <div class="user-card-title text-center">
            <h2>My bookings</h2>
          </div>
          <div class="user-card-details">
            <% if @user.bookings.count == 0 %>
              <div class="user-card-empty-list text-center">
                <p>You don't have any bookings yet!</p>
              </div>
            <% else %>
              <% @user.bookings.each do |booking| %>
                <div class="user-card-list" ">
                  <% if booking.menu.photos? %>
                    <%= cl_image_tag booking.menu.photos[0].path, crop: :fill, class: "avatar" %>
                  <% else %>
                    <%= image_tag "logo.png", class: "avatar" %>
                  <% end %>
                  <ul class="user-card-list-name">
                    <li> <%= booking.menu.name[0..40].gsub(/\s\w+\s*$/, '...') %></li>
                    <li> <%= booking.datetime.strftime("%A %d %B %H:%M") %> </li>
                  </ul>
                    <%= link_to "View", booking_path(booking), { class: "btn btn-danger list-view-button"} %>
                </div>
              <% end %>
            <% end %>
          </div>
          <%= link_to "View all bookings", user_bookings_path, { class: "btn btn-danger user-card-btn" } %>
        </div>
      </div>
    </div>
  </div>
</div>